kind: LocalConfig
apiversion: odo.dev/v1alpha1
ComponentSettings:
  Type: nodejs:10
  SourceLocation: ./
  SourceType: local
  Ports:
  - 8080/TCP
  Application: node-hello
  Project: node-hello
  Name: node-hello
