kind: LocalConfig
apiversion: odo.dev/v1alpha1
ComponentSettings:
  Type: nodejs:10
  SourceLocation: ./
  SourceType: local
  Ports:
  - 8080/TCP
  Application: dc-metro-map
  Project: crw-dcmm
  Name: dc-metro-map
